language: python
matrix:
  include:
  - os: linux
    dist: xenial
    python: 3.7
    env:
    - EXPECTED_PY="3.7"
  - os: osx
    language: generic
    env:
    - EXPECTED_PY="3.7"
    - PYTHON=3.7.0
    - PATH=/usr/local/bin:${PATH}
before_install:
- |
  if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    brew update
    brew outdated pyenv || brew upgrade pyenv
    brew install pyenv-virtualenv
    pyenv install $PYTHON
    export PYENV_VERSION=$PYTHON
    export PATH="/Users/travis/.pyenv/shims:${PATH}"
    pyenv-virtualenv venv
    source venv/bin/activate
    python --version
  fi
- pip install --upgrade pip setuptools
- python --version 2>&1 | grep -F "Python ${EXPECTED_PY}"
- pip --version | grep -F "(python ${EXPECTED_PY})"

script: python setup.py test

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: rbs392
  password:
    secure: "B18s0mDoH1q7u1tr1LY2yr2t7MjCHetF1C88853wT1imZwPllxYDzuFUe/OE9bmxr6gpm59Ta6WJ+7b2Y7/liodMMLfGk+A3msJm9YkOuLakvNyAy5JcV3eGnoYBxRULwy3mCbtTCZNQ0eXtPsRb/pkLAiATU3CaG8L+mo6lmszUR5IY9VOMcRHp6MIL9YO7uXHBNsbhxlkVNhMG0AvOesD2wgWa2hUkFo/uM5OzazpxISILiVz9aD658PCEVQu3C4Pooju+SzvCSWUhrrWZ23QH7qHa9WzTSmrQMJO5NYxNpzJhd7hILGjZVp1nOFNWz6ts499MNAc7KRaBStuX/vL0rusMkfFsMIiqV4eDaa4OGkdYIouqLvahU3qMD5UZK4gwYMhFvEXybeFHFtl3OoZJj3DcxnyK7QheaBa0lM0Wr2IIwMiaGnzXTLijBuI6VGEtL0pNJuH5Qy/b/ZmwMT4WXmuTOQxItsNRS4HryvfOzFBTsg2AtIrh0Lu2332beFD8U2cix64uKTvdhSuWxazAqzNLLdl69scSatekTfk0lUg3F0PR6fRhlnj5d26IU936O0zBFQLqetDYrRfGMfqdT7YgfEdIpX+uBiud2I3YeD9G8Fj4uGogdmbsWBGk53lFeR1qoUFPLhp7ws4rAAqoqoCq5wi4rJmnJH5XRwA="
  on:
    tags: true
    repo: zdatalake/zai
    condition: ${TRAVIS_OS_NAME} == "linux"
    dist: xenial
    python: 3.7
