language: python

matrix:
    include:
        - os: linux
          dist: xenial
          python: 2.7
          env:
            - TOXENV=py27
            - EXPECTED_PY="2.7"

        - os: linux
          dist: xenial
          python: 3.7
          env:
            - TOXENV=py37
            - EXPECTED_PY="3.7"

        - os: osx
          language: generic
          env:
            - TOXENV=py27
            - EXPECTED_PY="2.7"
            - PATH=/usr/local/bin:${PATH}

        - os: osx
          language: generic
          env:
            - TOXENV=py37
            - EXPECTED_PY="3.7"
            - PATH=/usr/local/bin:${PATH}


before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
        brew install python@2
        brew upgrade python
    fi
  - pip install --upgrade pip setuptools

install: pip install -U tox-travis

script: tox
